Logout and delete my account logic + modal-opener.service
SRBmartin/DRS pull request #7
Opened 2024-12-12 09:30 UTC by ivamladenovic

2024-12-12 11:44 UTC, MarkoKliska requested changes

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/application/features/user/commands/DeleteUserAccountCommand.py
> +            print(f"Error during delete operation: {str(ex)}")
Delete this print

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/application/services/user_service.py
> +            print(f"Received password: {password}")
Delete debug prints

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/application/services/user_service.py
> +            print(f"Before updating user, is_deleted: {user.is_deleted}")
Delete debug prints

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/application/services/user_service.py
> +            print(f"Error during delete operation: {str(ex)}")
Unnecessary print

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/domains/user/repositories.py
> +            db.session.add(user)  # Dodaj korisnika u sesiju
Delete unnecessary comments

2024-12-12 11:44 UTC, MarkoKliska commented on backend/api/app/infrastructure/persistence/migrations/versions/20241203_add_is_deleted_column_to_users.py
> +"""Adding is_deleted field to users table.
Delete this comment if it is not neccesarry

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/pages/profile-page/ui/delete-my-account/delete-my-account.component.ts
> +          console.log('Modal closed with result:', result);
Delete console.log

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/pages/profile-page/ui/delete-my-account/delete-my-account.component.ts
> +            console.log('Password:', password);
Delete these two console.logs

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/shared/generic-confirm-dialog/generic-confirm-dialog.component.ts
> +    console.log('Dialog initialized with:', { title: this.title, message: this.message });
Delete console.log

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/shared/ui/navbar/navbar.component.ts
> +        console.log('Modal closed with result:', result);
Delete console.log

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/shared/ui/navbar/navbar.component.ts
> +        console.error('Error in modal:', error);
Delete console.error

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                console.log('Logout successful:', response.message);
Delete console.log

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                console.log('Logout successful:', response.message);
Delete console.log

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/modal-opener.service.ts
> +      console.error('Error while closing modal:', error);
Delete console.error

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/modal-opener.service.ts
> +        console.error('Error while opening modal:', error);
Delete console.error

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                console.error('Error during logout:', err);
Delete console.error

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                console.error('Error during logout:', err);
Delete console.error

2024-12-12 11:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/pages/profile-page/ui/delete-my-account/delete-my-account.component.ts
> +          console.error('Error in modal:', error);
Delete console.error

2024-12-12 13:33 UTC, MarkoKliska approved these changes

2024-12-17 19:30 UTC, SRBmartin commented on frontend/survey-project/src/app/components/pages/profile-page/ui/delete-my-account/delete-my-account.component.ts
> +          title: 'DELETE ACCOUNT',
text-transform: uppercase;

2024-12-19 11:57 UTC, MarkoKliska requested changes

2024-12-19 11:57 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/dto/requests/user/logout-request.ts
> +export interface LogoutRequest {
There is no need for LogoutRequest interface, authorization is set in header by intercept.

2024-12-19 11:57 UTC, MarkoKliska commented on frontend/survey-project/src/app/components/shared/ui/navbar/navbar.component.ts
> +          this.executeLogout(); // Izvrši logout ako je potvrđeno
Delete unnecessary comment.

2024-12-19 12:08 UTC, MarkoKliska commented on backend/api/app/presentation/user/routes.py
>          current_app.logger.error(f"Error changing password: {str(e)}")
The code under this return will never be executed.

2024-12-19 13:29 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/user.service.ts
> +    logoutUser(): Observable<any> {
Use LogoutResponse instead of any in logoutUser(): Observable<any>

2024-12-19 13:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                this.router.navigate(['/login']);
User RouteNames instead of string.

2024-12-19 13:44 UTC, MarkoKliska commented on frontend/survey-project/src/app/shared/services/auth.service.ts
> +                this.router.navigate(['/register']);
Use RouteNames instead of string.

2024-12-19 14:01 UTC, MarkoKliska approved these changes

2024-12-19 14:02 UTC, merged